INCLUDE_WEBCAM = True
INCLUDE_API_CAMS = False
DISPLAY_VIDEOS = True
DRAW_LANDMARKS = True
DISPLAY_RESULTS_ON_FRAME = True

MODEL_HIDDEN_SIZE = 128
MODEL_OUTPUT_SIZE = 4
MODEL_L2_REGULARIZATION = 0.01
MODEL_RECURRENT_DROPOUT = 0.2
MODEL_DROPOUT = 0.2

API_BASE_URL = "http://localhost:5001"
API_CAMERA_ROUTE = "/cameras"
API_POLLING_PERIOD = 10
API_TIMEOUT = 5

CAMERA_STREAM_REFRESH_PERIOD = 5

MP_POSE_MODEL = 1

FALL_WINDOW_SIZE = 30
FALL_INPUT_SIZE = 36
FALL_PREDICTION_HISTORY_SIZE = 60
FALL_2_THRESHOLD = 8
FALL_1_AND_3_THRESHOLD = 8
INACTIVITY_SENSITIVTY = 0.005
INACTIVITY_TIME_LIMIT = 5